cp trans/1b0u*.pdb pdb-atp-hetatm
cp trans/1e79*.pdb pdb-atp-hetatm
cp trans/1g64*.pdb pdb-atp-hetatm
cp trans/1h8h*.pdb pdb-atp-hetatm
cp trans/1ji0*.pdb pdb-atp-hetatm
cp trans/1l2t*.pdb pdb-atp-hetatm
cp trans/1mab*.pdb pdb-atp-hetatm
cp trans/1mv5*.pdb pdb-atp-hetatm
cp trans/1nbm*.pdb pdb-atp-hetatm
cp trans/1ojl*.pdb pdb-atp-hetatm
cp trans/1q12*.pdb pdb-atp-hetatm
cp trans/1r0x*.pdb pdb-atp-hetatm
cp trans/1r0z*.pdb pdb-atp-hetatm
cp trans/1r10*.pdb pdb-atp-hetatm
cp trans/1tf7*.pdb pdb-atp-hetatm
cp trans/1u9i*.pdb pdb-atp-hetatm
cp trans/1vci*.pdb pdb-atp-hetatm
cp trans/1w7a*.pdb pdb-atp-hetatm
cp trans/1xef*.pdb pdb-atp-hetatm
cp trans/1xex*.pdb pdb-atp-hetatm
cp trans/1xf9*.pdb pdb-atp-hetatm
cp trans/1xfa*.pdb pdb-atp-hetatm
cp trans/1xmi*.pdb pdb-atp-hetatm
cp trans/1xmj*.pdb pdb-atp-hetatm
cp trans/2bbo*.pdb pdb-atp-hetatm
cp trans/2bbs*.pdb pdb-atp-hetatm
cp trans/2bbt*.pdb pdb-atp-hetatm
cp trans/2cbz*.pdb pdb-atp-hetatm
cp trans/2fgj*.pdb pdb-atp-hetatm
cp trans/2fgk*.pdb pdb-atp-hetatm
cp trans/2gbl*.pdb pdb-atp-hetatm
cp trans/2ixe*.pdb pdb-atp-hetatm
cp trans/2ixf*.pdb pdb-atp-hetatm
cp trans/2ixg*.pdb pdb-atp-hetatm
cp trans/2pze*.pdb pdb-atp-hetatm
cp trans/2pzf*.pdb pdb-atp-hetatm
cp trans/2pzg*.pdb pdb-atp-hetatm
cp trans/2r6g*.pdb pdb-atp-hetatm
cp trans/2r9v*.pdb pdb-atp-hetatm
cp trans/2wpd*.pdb pdb-atp-hetatm
cp trans/3b2q*.pdb pdb-atp-hetatm
cp trans/3dvl*.pdb pdb-atp-hetatm
cp trans/3eiu*.pdb pdb-atp-hetatm
cp trans/3fvq*.pdb pdb-atp-hetatm
cp trans/3j16*.pdb pdb-atp-hetatm
cp trans/3jzm*.pdb pdb-atp-hetatm
cp trans/3k09*.pdb pdb-atp-hetatm
cp trans/3k0a*.pdb pdb-atp-hetatm
cp trans/3k0c*.pdb pdb-atp-hetatm
cp trans/3k0e*.pdb pdb-atp-hetatm
cp trans/3k0f*.pdb pdb-atp-hetatm
cp trans/3lss*.pdb pdb-atp-hetatm
cp trans/3nh9*.pdb pdb-atp-hetatm
cp trans/3pjr*.pdb pdb-atp-hetatm
cp trans/3s1a*.pdb pdb-atp-hetatm
cp trans/3si7*.pdb pdb-atp-hetatm
cp trans/3vx4*.pdb pdb-atp-hetatm
cp trans/3zia*.pdb pdb-atp-hetatm
cp trans/4a6x*.pdb pdb-atp-hetatm
cp trans/4ai6*.pdb pdb-atp-hetatm
cp trans/4b2q*.pdb pdb-atp-hetatm
cp trans/4crm*.pdb pdb-atp-hetatm
cp trans/4dug*.pdb pdb-atp-hetatm
cp trans/4fwi*.pdb pdb-atp-hetatm
cp trans/4hut*.pdb pdb-atp-hetatm
cp trans/4ife*.pdb pdb-atp-hetatm
cp trans/4ijm*.pdb pdb-atp-hetatm
cp trans/4k8o*.pdb pdb-atp-hetatm
cp trans/4lya*.pdb pdb-atp-hetatm
cp trans/4m9s*.pdb pdb-atp-hetatm
cp trans/4n1a*.pdb pdb-atp-hetatm
cp trans/4nh0*.pdb pdb-atp-hetatm
cp trans/4o0m*.pdb pdb-atp-hetatm
cp trans/4p33*.pdb pdb-atp-hetatm
cp trans/4qc2*.pdb pdb-atp-hetatm
cp trans/4rh7*.pdb pdb-atp-hetatm
cp trans/4tl7*.pdb pdb-atp-hetatm
cp trans/4tsf*.pdb pdb-atp-hetatm
cp trans/4tt3*.pdb pdb-atp-hetatm
cp trans/4wz6*.pdb pdb-atp-hetatm
cp trans/4yds*.pdb pdb-atp-hetatm
cp trans/4ymu*.pdb pdb-atp-hetatm
cp trans/4ymv*.pdb pdb-atp-hetatm
cp trans/4z1m*.pdb pdb-atp-hetatm
cp trans/5dn6*.pdb pdb-atp-hetatm
cp trans/5fl7*.pdb pdb-atp-hetatm
cp trans/5h67*.pdb pdb-atp-hetatm
cp trans/5it5*.pdb pdb-atp-hetatm
cp trans/5j1s*.pdb pdb-atp-hetatm
cp trans/5jrj*.pdb pdb-atp-hetatm
cp trans/5koy*.pdb pdb-atp-hetatm
cp trans/5lil*.pdb pdb-atp-hetatm
cp trans/5lj6*.pdb pdb-atp-hetatm
cp trans/5lj7*.pdb pdb-atp-hetatm
cp trans/5mp9*.pdb pdb-atp-hetatm
cp trans/5nug*.pdb pdb-atp-hetatm
cp trans/5nwl*.pdb pdb-atp-hetatm
cp trans/5ofb*.pdb pdb-atp-hetatm
cp trans/5t4o*.pdb pdb-atp-hetatm
cp trans/5tf7*.pdb pdb-atp-hetatm
cp trans/5twv*.pdb pdb-atp-hetatm
cp trans/5uj7*.pdb pdb-atp-hetatm
cp trans/5vc7*.pdb pdb-atp-hetatm
cp trans/5vqa*.pdb pdb-atp-hetatm
cp trans/5w81*.pdb pdb-atp-hetatm
cp trans/5xmi*.pdb pdb-atp-hetatm
cp trans/5yud*.pdb pdb-atp-hetatm
cp trans/5z68*.pdb pdb-atp-hetatm
cp trans/5zxd*.pdb pdb-atp-hetatm
cp trans/6baa*.pdb pdb-atp-hetatm
cp trans/6bhu*.pdb pdb-atp-hetatm
cp trans/6c0v*.pdb pdb-atp-hetatm
cp trans/6c3o*.pdb pdb-atp-hetatm
cp trans/6c3p*.pdb pdb-atp-hetatm
cp trans/6d3r*.pdb pdb-atp-hetatm
cp trans/6d3s*.pdb pdb-atp-hetatm
cp trans/6fhs*.pdb pdb-atp-hetatm
cp trans/6gjq*.pdb pdb-atp-hetatm
cp trans/6gjs*.pdb pdb-atp-hetatm
cp trans/6gk4*.pdb pdb-atp-hetatm
cp trans/6gkd*.pdb pdb-atp-hetatm
cp trans/6hbu*.pdb pdb-atp-hetatm
cp trans/6hzm*.pdb pdb-atp-hetatm
cp trans/6j17*.pdb pdb-atp-hetatm
cp trans/6j18*.pdb pdb-atp-hetatm
cp trans/6jbj*.pdb pdb-atp-hetatm
cp trans/6jd5*.pdb pdb-atp-hetatm
cp trans/6m96*.pdb pdb-atp-hetatm
cp trans/6mat*.pdb pdb-atp-hetatm
cp trans/6mbn*.pdb pdb-atp-hetatm
cp trans/6mdm*.pdb pdb-atp-hetatm
cp trans/6msm*.pdb pdb-atp-hetatm
cp trans/6o1v*.pdb pdb-atp-hetatm
cp trans/6o2p*.pdb pdb-atp-hetatm
cp trans/6oa9*.pdb pdb-atp-hetatm
cp trans/6oqr*.pdb pdb-atp-hetatm
cp trans/6oqs*.pdb pdb-atp-hetatm
cp trans/6oqt*.pdb pdb-atp-hetatm
cp trans/6oqu*.pdb pdb-atp-hetatm
cp trans/6oqv*.pdb pdb-atp-hetatm
cp trans/6p07*.pdb pdb-atp-hetatm
cp trans/6p8v*.pdb pdb-atp-hetatm
cp trans/6pan*.pdb pdb-atp-hetatm
cp trans/6pao*.pdb pdb-atp-hetatm
cp trans/6paq*.pdb pdb-atp-hetatm
cp trans/6pqv*.pdb pdb-atp-hetatm
cp trans/6pz9*.pdb pdb-atp-hetatm
cp trans/6pza*.pdb pdb-atp-hetatm
cp trans/6pzi*.pdb pdb-atp-hetatm
cp trans/6qv0*.pdb pdb-atp-hetatm
cp trans/6r72*.pdb pdb-atp-hetatm
cp trans/6r81*.pdb pdb-atp-hetatm
cp trans/6raf*.pdb pdb-atp-hetatm
cp trans/6rag*.pdb pdb-atp-hetatm
cp trans/6rah*.pdb pdb-atp-hetatm
cp trans/6rai*.pdb pdb-atp-hetatm
cp trans/6raj*.pdb pdb-atp-hetatm
cp trans/6rak*.pdb pdb-atp-hetatm
cp trans/6ral*.pdb pdb-atp-hetatm
cp trans/6ram*.pdb pdb-atp-hetatm
cp trans/6rd4*.pdb pdb-atp-hetatm
cp trans/6ree*.pdb pdb-atp-hetatm
cp trans/6ref*.pdb pdb-atp-hetatm
cp trans/6rep*.pdb pdb-atp-hetatm
cp trans/6rer*.pdb pdb-atp-hetatm
cp trans/6res*.pdb pdb-atp-hetatm
cp trans/6ret*.pdb pdb-atp-hetatm
cp trans/6reu*.pdb pdb-atp-hetatm
cp trans/6s7p*.pdb pdb-atp-hetatm
cp trans/6tqe*.pdb pdb-atp-hetatm
cp trans/6uy0*.pdb pdb-atp-hetatm
cp trans/6wbs*.pdb pdb-atp-hetatm
cp trans/6wnq*.pdb pdb-atp-hetatm
cp trans/6wnr*.pdb pdb-atp-hetatm
cp trans/6zce*.pdb pdb-atp-hetatm
cp trans/6ze1*.pdb pdb-atp-hetatm
cp trans/6zu9*.pdb pdb-atp-hetatm
cp trans/6zyy*.pdb pdb-atp-hetatm
cp trans/6zz6*.pdb pdb-atp-hetatm
cp trans/7ahd*.pdb pdb-atp-hetatm
cp trans/7ai5*.pdb pdb-atp-hetatm
cp trans/7bg4*.pdb pdb-atp-hetatm
cp trans/7cag*.pdb pdb-atp-hetatm
cp trans/7cgn*.pdb pdb-atp-hetatm
cp trans/7ch0*.pdb pdb-atp-hetatm
cp trans/7crc*.pdb pdb-atp-hetatm
cp trans/7d09*.pdb pdb-atp-hetatm
cp trans/7dyi*.pdb pdb-atp-hetatm
cp trans/7dyk*.pdb pdb-atp-hetatm
cp trans/7e7q*.pdb pdb-atp-hetatm
cp trans/7ekl*.pdb pdb-atp-hetatm
cp trans/7jgr*.pdb pdb-atp-hetatm
cp trans/7jgs*.pdb pdb-atp-hetatm
cp trans/7jk6*.pdb pdb-atp-hetatm
cp trans/7jlv*.pdb pdb-atp-hetatm
cp trans/7jpp*.pdb pdb-atp-hetatm
cp trans/7k2t*.pdb pdb-atp-hetatm
cp trans/7l1q*.pdb pdb-atp-hetatm
cp trans/7l1r*.pdb pdb-atp-hetatm
cp trans/7l1s*.pdb pdb-atp-hetatm
cp trans/7lkz*.pdb pdb-atp-hetatm
cp trans/7ln2*.pdb pdb-atp-hetatm
cp trans/7m33*.pdb pdb-atp-hetatm
cp trans/7mi6*.pdb pdb-atp-hetatm
cp trans/7mit*.pdb pdb-atp-hetatm
cp trans/7mjo*.pdb pdb-atp-hetatm
cp trans/7mjp*.pdb pdb-atp-hetatm
cp trans/7mjq*.pdb pdb-atp-hetatm
cp trans/7n6i*.pdb pdb-atp-hetatm
cp trans/7njn*.pdb pdb-atp-hetatm
cp trans/7nyw*.pdb pdb-atp-hetatm
cp trans/7nyx*.pdb pdb-atp-hetatm
cp trans/7o17*.pdb pdb-atp-hetatm
cp trans/7ou4*.pdb pdb-atp-hetatm
cp trans/7ow8*.pdb pdb-atp-hetatm
cp trans/7oz1*.pdb pdb-atp-hetatm
cp trans/7p04*.pdb pdb-atp-hetatm
cp trans/7p05*.pdb pdb-atp-hetatm
cp trans/7p06*.pdb pdb-atp-hetatm
cp trans/7p2y*.pdb pdb-atp-hetatm
cp trans/7p3n*.pdb pdb-atp-hetatm
cp trans/7p3w*.pdb pdb-atp-hetatm
cp trans/7r8e*.pdb pdb-atp-hetatm
cp trans/7s5v*.pdb pdb-atp-hetatm
cp trans/7s5x*.pdb pdb-atp-hetatm
cp trans/7s5y*.pdb pdb-atp-hetatm
cp trans/7s5z*.pdb pdb-atp-hetatm
cp trans/7s60*.pdb pdb-atp-hetatm
cp trans/7s61*.pdb pdb-atp-hetatm
cp trans/7shm*.pdb pdb-atp-hetatm
cp trans/7sv7*.pdb pdb-atp-hetatm
cp trans/7svd*.pdb pdb-atp-hetatm
cp trans/7swl*.pdb pdb-atp-hetatm
cp trans/7t0v*.pdb pdb-atp-hetatm
cp trans/7t3i*.pdb pdb-atp-hetatm
cp trans/7t54*.pdb pdb-atp-hetatm
cp trans/7t55*.pdb pdb-atp-hetatm
cp trans/7t56*.pdb pdb-atp-hetatm
cp trans/7t57*.pdb pdb-atp-hetatm
cp trans/7tbw*.pdb pdb-atp-hetatm
cp trans/7tch*.pdb pdb-atp-hetatm
cp trans/7w02*.pdb pdb-atp-hetatm
